using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using Microsoft.Extensions.DependencyInjection;
using OodHelper.Data;
using CalendarEntity = OodHelper.Data.Entities.Calendar;

namespace OodHelper
{
    /// <summary>
    /// Interaction logic for Window2.xaml
    /// </summary>
    public partial class RaceChooser : Window
    {
        private readonly ICalendarRepository _calendarRepo;
        private DataTable cal;

        public RaceChooser()
        {
            InitializeComponent();
            // This dialog is not constructed through DI, so its repository is resolved from the
            // container here, mirroring SelectBoats and the other non-DI'd windows.
            _calendarRepo = App.Services.GetRequiredService<ICalendarRepository>();
            FilterRaces();
        }

        void CalGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DataGridTextColumn c = (DataGridTextColumn)CalGrid.Columns[cal.Columns["start_date"].Ordinal];
            c.Binding.StringFormat = "dd MMM yyyy HH:mm";
        }

        void RaceChooser_Loaded(object sender, RoutedEventArgs e)
        {
            DateTime? lr = _calendarRepo.GetLatestRaceDate(DateTime.Today.AddDays(1.0));
            DateSel.SelectedDate = lr?.Date ?? DateTime.Today;
        }

        private void SetGridSource()
        {
            CalGrid.ItemsSource = cal.DefaultView;
            if (cal.Rows.Count > 0)
                CalGrid.SelectedIndex = 0;
        }

        System.Timers.Timer t = null;

        void Eventname_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (t == null)
                t = new System.Timers.Timer(500);
            else
                t.Stop();
            t.AutoReset = false;
            t.Elapsed += new System.Timers.ElapsedEventHandler(t_Elapsed);
            t.Start();
        }

        void t_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
        {
            try
            {
                Dispatcher.Invoke(new dFilterRaces(FilterRaces), null);
            }
            catch (Exception ex)
            {
                string x = ex.Message;
            }
        }

        public delegate void dFilterRaces();

        public void FilterRaces()
        {
            try
            {
                IReadOnlyList<DateTime> days = _calendarRepo.GetRaceDays(Eventname.Text);
                DateSel.BlackoutDates.Clear();
                if (days.Count > 0)
                {
                    DateSel.DisplayDateStart = days[0];
                    DateSel.DisplayDateEnd = days[days.Count - 1];

                    DateTime? lr = null;
                    for (int i = 0; i < days.Count - 1; i++)
                    {
                        CalendarDateRange r = new CalendarDateRange(days[i], days[i + 1]);
                        if (lr == null && r.Start >= DateTime.Today) lr = r.Start;
                        if (r.End - r.Start > new TimeSpan(1, 0, 0, 0))
                        {
                            r.End = r.End.AddDays(-1);
                            r.Start = r.Start.AddDays(1);
                            DateSel.BlackoutDates.Add(r);
                        }
                    }
                    if (lr == null) lr = days[days.Count - 1];
                    DateSel.SelectedDate = lr.Value;
                    if (DateSel.SelectedDate.HasValue)
                        DateSel.DisplayDate = DateSel.SelectedDate.Value;
                }

                if (CalGrid.ItemsSource is DataView dv)
                    dv.RowFilter = "event LIKE '%" + Eventname.Text + "%'";
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private static DataTable BuildCalendarTable(IReadOnlyList<CalendarEntity> races)
        {
            //
            // Reproduces the column set the old `SELECT rid, start_date, event, class, raced`
            // produced, so the auto-generated grid columns, the start_date formatter and
            // setChosenRaces (which reads rid/start_date by name) keep working unchanged.
            //
            DataTable dt = new DataTable { TableName = "calendar" };
            dt.Columns.Add(new DataColumn("rid", typeof(int)));
            dt.Columns.Add(new DataColumn("start_date", typeof(DateTime)));
            dt.Columns.Add(new DataColumn("event", typeof(string)));
            dt.Columns.Add(new DataColumn("class", typeof(string)));
            dt.Columns.Add(new DataColumn("raced", typeof(bool)));
            foreach (var c in races)
            {
                DataRow r = dt.NewRow();
                r["rid"] = c.Rid;
                r["start_date"] = (object)c.StartDate ?? DBNull.Value;
                r["event"] = (object)c.Event ?? DBNull.Value;
                r["class"] = (object)c.Class ?? DBNull.Value;
                r["raced"] = (object)c.Raced ?? DBNull.Value;
                dt.Rows.Add(r);
            }
            dt.AcceptChanges();
            return dt;
        }

        private void Window_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.F3)
                Eventname.Focus();
            if (e.Key == Key.W && (e.KeyboardDevice.IsKeyDown(Key.LeftCtrl) || e.KeyboardDevice.IsKeyDown(Key.RightCtrl)))
                setChosenRaces();
        }

        private void buttonResults_Click(object sender, RoutedEventArgs e)
        {
            setChosenRaces();
        }

        public int[] Rids
        {
            get
            {
                return rids;
            }
        }
        private int[] rids;

        private void setChosenRaces()
        {
            DialogResult = true;
            int rowIndex = CalGrid.SelectedIndex;
            if (CalGrid.SelectedItem == null) return;
            int r = (int) ((DataRowView)CalGrid.SelectedItem).Row["rid"];
            DateTime rd = (DateTime) ((DataRowView) CalGrid.SelectedItem).Row["start_date"];
            TimeSpan st = rd.TimeOfDay;
            ArrayList res = new ArrayList();
            res.Add(r);

            if (st.ToString("hhmm") != "0000")
            {
                for (int i = rowIndex - 1; i >= 0; i--)
                {
                    DateTime d = (DateTime)((DataRowView)CalGrid.Items[i]).Row["start_date"];
                    if ((rd - d).TotalMinutes > 15)
                        break;
                    res.Add(((DataRowView)CalGrid.Items[i]).Row["rid"]);
                }
                for (int i = rowIndex + 1; i < CalGrid.Items.Count; i++)
                {
                    DateTime d = (DateTime)((DataRowView)CalGrid.Items[i]).Row["start_date"];
                    if ((d - rd).TotalMinutes > 15)
                        break;
                    res.Add(((DataRowView)CalGrid.Items[i]).Row["rid"]);
                }
            }
            res.Sort();
            rids = (int[]) res.ToArray(Type.GetType("System.Int32"));
            this.Close();
        }

        private void Close_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }

        private void DateSel_SelectedDatesChanged(object sender, SelectionChangedEventArgs e)
        {
            if (DateSel.SelectedDate.HasValue)
            {
                cal = BuildCalendarTable(_calendarRepo.GetRacesOnDay(DateSel.SelectedDate.Value));
                SetGridSource();
            }
        }

        private void buttonToday_Click(object sender, RoutedEventArgs e)
        {
            if (DateSel.DisplayDateStart >= DateTime.Today)
                DateSel.SelectedDate = DateSel.DisplayDateStart;
            else if (DateSel.DisplayDateEnd <= DateTime.Today)
                DateSel.SelectedDate = DateSel.DisplayDateEnd;
            else
            {
                DateTime sel = DateTime.Today;
                bool isSet = false;
                while (!isSet)
                {
                    try
                    {
                        DateSel.SelectedDate = sel;
                        isSet = true;
                    }
                    catch
                    {
                        sel = sel.AddDays(-1);
                    }
                }
            }
            if (DateSel.SelectedDate.HasValue)
                DateSel.DisplayDate = DateSel.SelectedDate.Value;
        }
    }
}
