using System;
using System.Collections;
using System.Data;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace OodHelper.net
{
    /// <summary>
    /// Interaction logic for TestPage.xaml
    /// </summary>
    [Svn("$Id$")]
    public partial class RollingHandicapResultsPage : Page
    {
        DataTable rd;

        public RollingHandicapResultsPage(RaceEdit red)
        {
            InitializeComponent();

            red.scorer.Calculate(red.Rid);
            RaceDate.Text = "Date of Race: " + red.RaceDate.ToShortDateString();
            EventDescription.Text = red.RaceName;
            OodName.Text = "OOD: " + red.Ood;
            Start.Text = "Start: " + red.start.Text;
            Sct.Text = "SCT: " + Common.HMS(red.scorer.StandardCorrectedTime);

            Db c = new Db("SELECT b.boatname Boat, b.boatclass [Class], b.sailno [Sail No], r.rolling_handicap as Hcap, " +
                "r.finish_date Finish, r.elapsed Elapsed, r.laps Laps, r.corrected Corrected, r.place Pos, " +
                "CASE WHEN override_points = 0 THEN points ELSE override_points END Pts, " +
                "r.achieved_handicap Achp, r.new_rolling_handicap [nhcp], r.performance_index PI, r.c C, r.a A, " +
                "r.handicap_status PY " +
                "FROM boats b INNER JOIN races r ON r.bid = b.bid " +
                "WHERE r.rid = @rid " +
                "ORDER BY place");
            Hashtable p = new Hashtable();
            p["rid"] = red.Rid;

            rd = c.GetData(p);
            foreach (DataRow r in rd.Rows)
            {
                if ((int)r["Pos"] == 999)
                {
                    r["elapsed"] = DBNull.Value;
                    r["laps"] = DBNull.Value;
                    r["corrected"] = DBNull.Value;
                    r["Pos"] = DBNull.Value;
                    r["Pts"] = DBNull.Value;
                    r["achp"] = DBNull.Value;
                    r["pi"] = DBNull.Value;
                    r["nhcp"] = DBNull.Value;
                    r["c"] = DBNull.Value;
                    r["a"] = DBNull.Value;
                    r["py"] = DBNull.Value;
                }
            }
            Results.ItemsSource = rd.DefaultView;
        }

        private void Results_Loaded(object sender, RoutedEventArgs e)
        {
        }

        private void Results_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DataGridTextColumn col = (DataGridTextColumn)Results.Columns[rd.Columns["elapsed"].Ordinal];
            Binding b = (Binding)col.Binding;
            b.Converter = new IntTimeSpan();
            col.Binding = b;

            col = (DataGridTextColumn)Results.Columns[rd.Columns["corrected"].Ordinal];
            b = (Binding)col.Binding;
            b.Converter = new DoubleTimeSpan();
            col.Binding = b;

            SetRightAlignment(Results.Columns[rd.Columns["hcap"].Ordinal]);
            SetRightAlignment(Results.Columns[rd.Columns["Pos"].Ordinal]);
            SetRightAlignment(Results.Columns[rd.Columns["Pts"].Ordinal]);
            SetRightAlignment(Results.Columns[rd.Columns["achp"].Ordinal]);
            SetRightAlignment(Results.Columns[rd.Columns["pi"].Ordinal]);
            SetRightAlignment(Results.Columns[rd.Columns["nhcp"].Ordinal]);

            Hashtable widths = new Hashtable();
            widths["Boat"] = 22.0;
            widths["Class"] = 19.0;
            widths["Sail No"] = 9.0;
            widths["Hcap"] = 6.0;
            widths["Finish"] = 10.5;
            widths["Elapsed"] = 10.5;
            widths["Laps"] = 4.5;
            widths["Corrected"] = 10.5;
            widths["Pos"] = 5.0;
            widths["Pts"] = 5.0;
            widths["achp"] = 6.0;
            widths["pi"] = 6.0;
            widths["nhcp"] = 6.0;
            widths["c"] = .75;
            widths["a"] = .75;
            widths["py"] = 1.5;

            double sumWidths = 0;
            foreach (double w in widths.Values)
                sumWidths += w;

            double printableWidth = Width - PageMainGrid.Margin.Left - PageMainGrid.Margin.Right;

            foreach (string colname in widths.Keys)
                Results.Columns[rd.Columns[colname].Ordinal].Width = printableWidth * ((double)widths[colname]) / sumWidths - 4;

            Results.Columns[rd.Columns["achp"].Ordinal].Header = "Achd\nHcap";
            Results.Columns[rd.Columns["nhcp"].Ordinal].Header = "New\nHcap";
        }

        private void SetRightAlignment(DataGridColumn c)
        {
            c.CellStyle = this.Resources["RightAlignCell"] as Style;
            c.HeaderStyle = this.Resources["RightAlignHeader"] as Style;
        }

        private void Results_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            Results.SelectedItems.Clear();
        }
    }
}
