using System.Windows.Controls;
using OodHelper.Results;

namespace OodHelper
{
    /// <summary>
    /// Interaction logic for SeriesDisplay.xaml. A thin view over <see cref="SeriesDisplayViewModel"/>:
    /// the fixed columns bind to the VM and the per-race columns are generated by the
    /// <c>SeriesRaceColumns</c> behaviour. Replaces the old DataTable/Db code-behind.
    /// </summary>
    public partial class SeriesDisplay : UserControl
    {
        public SeriesDisplayViewModel ViewModel { get; }

        public SeriesDisplay(SeriesDisplayViewModel viewModel)
        {
            InitializeComponent();
            ViewModel = viewModel;
            DataContext = viewModel;
        }
    }
}
