// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OodHelper.Data;

#nullable disable

namespace OodHelper.Migrations
{
    [DbContext(typeof(OodHelperContext))]
    [Migration("20260630191302_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OodHelper.Data.Entities.Boat", b =>
                {
                    b.Property<int>("Bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("bid")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int?>("Beaten")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beaten");

                    b.Property<string>("Berth")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("berth");

                    b.Property<string>("Boatclass")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("boatclass");

                    b.Property<string>("Boatmemo")
                        .HasColumnType("TEXT")
                        .HasColumnName("boatmemo");

                    b.Property<string>("Boatname")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("boatname");

                    b.Property<int?>("CrewSkillFactor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("crew_skill_factor");

                    b.Property<string>("Deviations")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("deviations");

                    b.Property<bool?>("Dinghy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dinghy");

                    b.Property<int?>("Distance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distance");

                    b.Property<string>("EnginePropeller")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("engine_propeller");

                    b.Property<string>("HandicapStatus")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("handicap_status");

                    b.Property<bool?>("Hired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hired");

                    b.Property<string>("Hulltype")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("hulltype");

                    b.Property<string>("Keel")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("keel");

                    b.Property<int?>("OpenHandicap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("open_handicap");

                    b.Property<string>("P")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("p");

                    b.Property<int?>("RollingHandicap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rolling_handicap");

                    b.Property<bool?>("S")
                        .HasColumnType("INTEGER")
                        .HasColumnName("s");

                    b.Property<string>("Sailno")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("sailno");

                    b.Property<decimal?>("SmallCatHandicapRating")
                        .HasColumnType("TEXT")
                        .HasColumnName("small_cat_handicap_rating");

                    b.Property<string>("Subscription")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("subscription");

                    b.Property<Guid?>("Uid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uid");

                    b.HasKey("Bid");

                    b.ToTable("boats", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Calendar", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("rid");

                    b.Property<bool?>("Approved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved");

                    b.Property<string>("Class")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("class");

                    b.Property<string>("Course")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("course");

                    b.Property<string>("CourseChoice")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("course_choice");

                    b.Property<string>("Event")
                        .HasMaxLength(34)
                        .HasColumnType("TEXT")
                        .HasColumnName("event");

                    b.Property<int?>("Extension")
                        .HasColumnType("INTEGER")
                        .HasColumnName("extension");

                    b.Property<string>("Flag")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("flag");

                    b.Property<string>("Handicapping")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("handicapping");

                    b.Property<bool?>("IsRace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_race");

                    b.Property<int?>("LapsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("laps_completed");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT")
                        .HasColumnName("memo");

                    b.Property<string>("Ood")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("ood");

                    b.Property<string>("PriceCode")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("price_code");

                    b.Property<bool?>("Raced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("raced");

                    b.Property<string>("Racetype")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("racetype");

                    b.Property<DateTime?>("ResultCalculated")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_calculated");

                    b.Property<double?>("StandardCorrectedTime")
                        .HasColumnType("REAL")
                        .HasColumnName("standard_corrected_time");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<int?>("TimeLimitDelta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_limit_delta");

                    b.Property<DateTime?>("TimeLimitFixed")
                        .HasColumnType("TEXT")
                        .HasColumnName("time_limit_fixed");

                    b.Property<string>("TimeLimitType")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_limit_type");

                    b.Property<string>("Venue")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("venue");

                    b.Property<int?>("Visitors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visitors");

                    b.Property<string>("WindDirection")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("wind_direction");

                    b.Property<string>("WindSpeed")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("wind_speed");

                    b.HasKey("Rid");

                    b.ToTable("calendar", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.CalendarSeriesJoin", b =>
                {
                    b.Property<int>("Sid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sid");

                    b.Property<int>("Rid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rid");

                    b.HasKey("Sid", "Rid");

                    b.HasIndex("Rid");

                    b.ToTable("calendar_series_join", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.PortsmouthNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("class_name");

                    b.Property<string>("Engine")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("engine");

                    b.Property<string>("Keel")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("keel");

                    b.Property<int?>("NoOfCrew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("no_of_crew");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<string>("Rig")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("rig");

                    b.Property<string>("Spinnaker")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("spinnaker");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("portsmouth_numbers", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Race", b =>
                {
                    b.Property<int>("Rid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rid");

                    b.Property<int>("Bid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bid");

                    b.Property<string>("A")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("a");

                    b.Property<int?>("AchievedHandicap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("achieved_handicap");

                    b.Property<string>("C")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("c");

                    b.Property<double?>("Corrected")
                        .HasColumnType("REAL")
                        .HasColumnName("corrected");

                    b.Property<int?>("Elapsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elapsed");

                    b.Property<string>("FinishCode")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_code");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_date");

                    b.Property<string>("HandicapStatus")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("handicap_status");

                    b.Property<DateTime?>("InterimDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("interim_date");

                    b.Property<int?>("Laps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("laps");

                    b.Property<DateTime?>("LastEdit")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_edit");

                    b.Property<int?>("NewRollingHandicap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_rolling_handicap");

                    b.Property<int?>("OpenHandicap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("open_handicap");

                    b.Property<double?>("OverridePoints")
                        .HasColumnType("REAL")
                        .HasColumnName("override_points");

                    b.Property<int?>("PerformanceIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("performance_index");

                    b.Property<int?>("Place")
                        .HasColumnType("INTEGER")
                        .HasColumnName("place");

                    b.Property<double?>("Points")
                        .HasColumnType("REAL")
                        .HasColumnName("points");

                    b.Property<bool?>("RestrictedSail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("restricted_sail");

                    b.Property<int?>("RollingHandicap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rolling_handicap");

                    b.Property<double?>("StandardCorrected")
                        .HasColumnType("REAL")
                        .HasColumnName("standard_corrected");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.HasKey("Rid", "Bid");

                    b.HasIndex("Bid");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.SelectRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("Application")
                        .HasColumnType("INTEGER")
                        .HasColumnName("application");

                    b.Property<int?>("Condition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition");

                    b.Property<string>("Field")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("field");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal?>("NumberBound1")
                        .HasColumnType("TEXT")
                        .HasColumnName("number_bound1");

                    b.Property<decimal?>("NumberBound2")
                        .HasColumnType("TEXT")
                        .HasColumnName("number_bound2");

                    b.Property<Guid?>("Parent")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent");

                    b.Property<string>("StringValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("string_value");

                    b.HasKey("Id")
                        .HasName("PK_select_rule");

                    b.ToTable("select_rules", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Series", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("sid");

                    b.Property<string>("Discards")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("discards");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("sname");

                    b.HasKey("Sid");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.SeriesResult", b =>
                {
                    b.Property<int>("Sid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sid");

                    b.Property<string>("Division")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<int>("Bid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bid");

                    b.Property<int?>("Entered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entered");

                    b.Property<double?>("Gross")
                        .HasColumnType("REAL")
                        .HasColumnName("gross");

                    b.Property<double?>("Nett")
                        .HasColumnType("REAL")
                        .HasColumnName("nett");

                    b.Property<int?>("Place")
                        .HasColumnType("INTEGER")
                        .HasColumnName("place");

                    b.HasKey("Sid", "Division", "Bid");

                    b.ToTable("series_results", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Update", b =>
                {
                    b.Property<int?>("Dummy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dummy");

                    b.Property<DateTime?>("Upload")
                        .HasColumnType("TEXT")
                        .HasColumnName("upload");

                    b.ToTable("updates", (string)null);
                });

            modelBuilder.Entity("OodHelper.Data.Entities.CalendarSeriesJoin", b =>
                {
                    b.HasOne("OodHelper.Data.Entities.Calendar", null)
                        .WithMany()
                        .HasForeignKey("Rid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_calendar_series_join_calendar");

                    b.HasOne("OodHelper.Data.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("Sid")
                        .IsRequired()
                        .HasConstraintName("FK_calendar_series_join_series");
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Race", b =>
                {
                    b.HasOne("OodHelper.Data.Entities.Boat", "BidNavigation")
                        .WithMany("Races")
                        .HasForeignKey("Bid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_races_boats");

                    b.HasOne("OodHelper.Data.Entities.Calendar", "RidNavigation")
                        .WithMany("Races")
                        .HasForeignKey("Rid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_races_calendar");

                    b.Navigation("BidNavigation");

                    b.Navigation("RidNavigation");
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Boat", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("OodHelper.Data.Entities.Calendar", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
